// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosgradoBot.Data;

namespace PosgradoBot.Migrations
{
    [DbContext(typeof(DataBaseService))]
    partial class DataBaseServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PosgradoBot.Common.Model.Curses.Curses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("costo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Curses");
                });

            modelBuilder.Entity("PosgradoBot.Common.Model.Curses.PaysModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("cuotaCinco")
                        .HasColumnType("float");

                    b.Property<double>("cuotaCuatro")
                        .HasColumnType("float");

                    b.Property<double>("cuotaDos")
                        .HasColumnType("float");

                    b.Property<double>("cuotaSeis")
                        .HasColumnType("float");

                    b.Property<double>("cuotaTres")
                        .HasColumnType("float");

                    b.Property<double>("cuotaUno")
                        .HasColumnType("float");

                    b.Property<string>("idCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Pays");
                });

            modelBuilder.Entity("PosgradoBot.Common.Model.Preinscription.PreinscriptionModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellidoM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidoP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ciemi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoexemi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estcivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("excarrera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaegreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechanac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fuerza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCurse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lugarnac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("names")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profesion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Preinscription");
                });

            modelBuilder.Entity("PosgradoBot.Common.Model.Qualification.QualificationModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("idUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Qualification");
                });

            modelBuilder.Entity("PosgradoBot.Common.Model.Tickets.TicketModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("PosgradoBot.Common.Model.User.UserModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("userNameChannel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
